version: '3'
services:
  web:
    build: .
    volumes:
      - .:/Lost_And_Found
    links:
      - mysql
      - redis
      - worker
    ports:
      - "5000:5000"
  mysql:
    image: "mysql:5.6"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/data/db:/var/lib/mysql
  redis:
    image: redis:latest
    hostname: redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: worker
    entrypoint: celery
    command: -A app.emailverify.emailverify.celery worker --loglevel=DEBUG
    volumes:
      - .:/Lost_And_Found
    links:
      - redis
    depends_on:
      - redis